spring:
  application:
    name: billtracker

billtracker:
  oauth2:
    providers:
      google:
        tokenEndpoint: https://oauth2.googleapis.com/token
        clientSecret:
        clientId:
        redirectUri: