/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmUserResponse
 */
export interface ConfirmUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ConfirmUserResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ConfirmUserResponse interface.
 */
export function instanceOfConfirmUserResponse(value: object): value is ConfirmUserResponse {
    return true;
}

export function ConfirmUserResponseFromJSON(json: any): ConfirmUserResponse {
    return ConfirmUserResponseFromJSONTyped(json, false);
}

export function ConfirmUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ConfirmUserResponseToJSON(json: any): ConfirmUserResponse {
    return ConfirmUserResponseToJSONTyped(json, false);
}

export function ConfirmUserResponseToJSONTyped(value?: ConfirmUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

