/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRecurringExpenseCreatorRequest
 */
export interface CreateRecurringExpenseCreatorRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateRecurringExpenseCreatorRequest
     */
    recursEveryCalendarDay: number;
    /**
     * 
     * @type {number}
     * @memberof CreateRecurringExpenseCreatorRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRecurringExpenseCreatorRequest
     */
    description: string;
}

/**
 * Check if a given object implements the CreateRecurringExpenseCreatorRequest interface.
 */
export function instanceOfCreateRecurringExpenseCreatorRequest(value: object): value is CreateRecurringExpenseCreatorRequest {
    if (!('recursEveryCalendarDay' in value) || value['recursEveryCalendarDay'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateRecurringExpenseCreatorRequestFromJSON(json: any): CreateRecurringExpenseCreatorRequest {
    return CreateRecurringExpenseCreatorRequestFromJSONTyped(json, false);
}

export function CreateRecurringExpenseCreatorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecurringExpenseCreatorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recursEveryCalendarDay': json['recursEveryCalendarDay'],
        'amount': json['amount'],
        'description': json['description'],
    };
}

export function CreateRecurringExpenseCreatorRequestToJSON(json: any): CreateRecurringExpenseCreatorRequest {
    return CreateRecurringExpenseCreatorRequestToJSONTyped(json, false);
}

export function CreateRecurringExpenseCreatorRequestToJSONTyped(value?: CreateRecurringExpenseCreatorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recursEveryCalendarDay': value['recursEveryCalendarDay'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

