/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntroductorySettings
 */
export interface IntroductorySettings {
    /**
     * 
     * @type {string}
     * @memberof IntroductorySettings
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof IntroductorySettings
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof IntroductorySettings
     */
    birthday?: Date;
}

/**
 * Check if a given object implements the IntroductorySettings interface.
 */
export function instanceOfIntroductorySettings(value: object): value is IntroductorySettings {
    return true;
}

export function IntroductorySettingsFromJSON(json: any): IntroductorySettings {
    return IntroductorySettingsFromJSONTyped(json, false);
}

export function IntroductorySettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntroductorySettings {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
    };
}

export function IntroductorySettingsToJSON(json: any): IntroductorySettings {
    return IntroductorySettingsToJSONTyped(json, false);
}

export function IntroductorySettingsToJSONTyped(value?: IntroductorySettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday']).toISOString().substring(0,10)),
    };
}

