/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOneOffExpenseRequest
 */
export interface CreateOneOffExpenseRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateOneOffExpenseRequest
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateOneOffExpenseRequest
     */
    date: Date;
}

/**
 * Check if a given object implements the CreateOneOffExpenseRequest interface.
 */
export function instanceOfCreateOneOffExpenseRequest(value: object): value is CreateOneOffExpenseRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function CreateOneOffExpenseRequestFromJSON(json: any): CreateOneOffExpenseRequest {
    return CreateOneOffExpenseRequestFromJSONTyped(json, false);
}

export function CreateOneOffExpenseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOneOffExpenseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'date': (new Date(json['date'])),
    };
}

export function CreateOneOffExpenseRequestToJSON(json: any): CreateOneOffExpenseRequest {
    return CreateOneOffExpenseRequestToJSONTyped(json, false);
}

export function CreateOneOffExpenseRequestToJSONTyped(value?: CreateOneOffExpenseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'date': ((value['date']).toISOString()),
    };
}

