/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleTokenRequest
 */
export interface HandleTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof HandleTokenRequest
     */
    code: string;
}

/**
 * Check if a given object implements the HandleTokenRequest interface.
 */
export function instanceOfHandleTokenRequest(value: object): value is HandleTokenRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function HandleTokenRequestFromJSON(json: any): HandleTokenRequest {
    return HandleTokenRequestFromJSONTyped(json, false);
}

export function HandleTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function HandleTokenRequestToJSON(json: any): HandleTokenRequest {
    return HandleTokenRequestToJSONTyped(json, false);
}

export function HandleTokenRequestToJSONTyped(value?: HandleTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

