/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleOAuth2TokenResponse
 */
export interface HandleOAuth2TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof HandleOAuth2TokenResponse
     */
    jwt: string;
}

/**
 * Check if a given object implements the HandleOAuth2TokenResponse interface.
 */
export function instanceOfHandleOAuth2TokenResponse(value: object): value is HandleOAuth2TokenResponse {
    if (!('jwt' in value) || value['jwt'] === undefined) return false;
    return true;
}

export function HandleOAuth2TokenResponseFromJSON(json: any): HandleOAuth2TokenResponse {
    return HandleOAuth2TokenResponseFromJSONTyped(json, false);
}

export function HandleOAuth2TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleOAuth2TokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jwt': json['jwt'],
    };
}

export function HandleOAuth2TokenResponseToJSON(json: any): HandleOAuth2TokenResponse {
    return HandleOAuth2TokenResponseToJSONTyped(json, false);
}

export function HandleOAuth2TokenResponseToJSONTyped(value?: HandleOAuth2TokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jwt': value['jwt'],
    };
}

