/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringExpenseEventCreator
 */
export interface RecurringExpenseEventCreator {
    /**
     * 
     * @type {string}
     * @memberof RecurringExpenseEventCreator
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof RecurringExpenseEventCreator
     */
    recursEveryCalendarDay: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringExpenseEventCreator
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringExpenseEventCreator
     */
    description: string;
}

/**
 * Check if a given object implements the RecurringExpenseEventCreator interface.
 */
export function instanceOfRecurringExpenseEventCreator(value: object): value is RecurringExpenseEventCreator {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('recursEveryCalendarDay' in value) || value['recursEveryCalendarDay'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function RecurringExpenseEventCreatorFromJSON(json: any): RecurringExpenseEventCreator {
    return RecurringExpenseEventCreatorFromJSONTyped(json, false);
}

export function RecurringExpenseEventCreatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringExpenseEventCreator {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'recursEveryCalendarDay': json['recursEveryCalendarDay'],
        'amount': json['amount'],
        'description': json['description'],
    };
}

export function RecurringExpenseEventCreatorToJSON(json: any): RecurringExpenseEventCreator {
    return RecurringExpenseEventCreatorToJSONTyped(json, false);
}

export function RecurringExpenseEventCreatorToJSONTyped(value?: RecurringExpenseEventCreator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'recursEveryCalendarDay': value['recursEveryCalendarDay'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

