/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetIntroductorySettingsRequest
 */
export interface SetIntroductorySettingsRequest {
    /**
     * 
     * @type {string}
     * @memberof SetIntroductorySettingsRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof SetIntroductorySettingsRequest
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof SetIntroductorySettingsRequest
     */
    birthday: Date;
}

/**
 * Check if a given object implements the SetIntroductorySettingsRequest interface.
 */
export function instanceOfSetIntroductorySettingsRequest(value: object): value is SetIntroductorySettingsRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('birthday' in value) || value['birthday'] === undefined) return false;
    return true;
}

export function SetIntroductorySettingsRequestFromJSON(json: any): SetIntroductorySettingsRequest {
    return SetIntroductorySettingsRequestFromJSONTyped(json, false);
}

export function SetIntroductorySettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetIntroductorySettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'birthday': (new Date(json['birthday'])),
    };
}

export function SetIntroductorySettingsRequestToJSON(json: any): SetIntroductorySettingsRequest {
    return SetIntroductorySettingsRequestToJSONTyped(json, false);
}

export function SetIntroductorySettingsRequestToJSONTyped(value?: SetIntroductorySettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'birthday': ((value['birthday']).toISOString().substring(0,10)),
    };
}

