/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateSessionResponse
 */
export interface ValidateSessionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ValidateSessionResponse
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the ValidateSessionResponse interface.
 */
export function instanceOfValidateSessionResponse(value: object): value is ValidateSessionResponse {
    return true;
}

export function ValidateSessionResponseFromJSON(json: any): ValidateSessionResponse {
    return ValidateSessionResponseFromJSONTyped(json, false);
}

export function ValidateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function ValidateSessionResponseToJSON(json: any): ValidateSessionResponse {
    return ValidateSessionResponseToJSONTyped(json, false);
}

export function ValidateSessionResponseToJSONTyped(value?: ValidateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
    };
}

