name: Target-specific command
description: Run a shell command dependning on the intended deployment target
inputs:
  production:
    description: Shell command to run for production
    required: true
  develop:
    description: Shell command to run for develop
    required: true
  working_directory:
    description: Working directory to execute the commands in.
    required: false
runs:
  using: composite
  steps:
    - name: Set environment variable based on branch
      run: |
        if [[ -n "${{ inputs.working_directory }}" ]]; then
          cd ${{ inputs.working_directory }}
        fi

        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          ${{ inputs.production }}
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          ${{ inputs.develop }}
        else
          echo "Invalid ref: ${{ github.ref }}"
          exit 1
        fi
      shell: bash