name: Target-specific command
description: Run a shell command dependning on the intended deployment target. This also sets the $TARGET environment variable.
inputs:
  production:
    description: Shell command to run for production
    required: true
  develop:
    description: Shell command to run for develop
    required: true
  working_directory:
    description: Working directory to execute the commands in.
    required: false
runs:
  using: composite
  steps:
    - name: Set environment variable based on branch
      run: |
        if [[ -n "${{ inputs.working_directory }}" ]]; then
          cd ${{ inputs.working_directory }}
        fi

        if [[ "${{env.TARGET}}" == "production" ]]; then
          ${{ inputs.production }}
        elif [[ "${{env.TARGET}}" == "develop" ]]; then
          ${{ inputs.develop }}
        else
          echo "Invalid target: ${{env.TARGET}}. Did you run the 'set-target' action?
          exit 1
        fi
      shell: bash