name: Set Target
description: Set the end-goal target for this run. This will determine if we're going to production or develop.
runs:
  using: composite
  steps:
    - name: Set environment variable based on branch
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "ENV=production" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]
          echo "ENV=develop" >> $GITHUB_ENV
      shell: bash