name: Build and Deploy
on:
  release:
    types:
      - created
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Install dependencies
      run: cd src/main/frontend && npm i
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: |
          target/billtracker-0.0.1.jar
  publish_maven:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}
      - uses: actions/download-artifact@v4
        with:
          name: app
      - run: ls
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s ./settings.xml -Dgithub.token=${{ github.token}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  publish_container:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3