name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
jobs:
  init:
    runs-on: ubuntu-24.04
    steps:
      - name: Set Target
        uses: ./.github/actions/set-target
  
  backend_oci_container:
    runs-on: ubuntu-24.04
    needs:
      - init
    defaults:
      run:
        working-directory: ./backend
    environment: ${{ env.TARGET }}
    steps:
      - run: ls