name: Build and Publish Maven Artifact
on:
  release:
    types:
      - created
  push: 
    branches: 
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Install dependencies
      run: cd src/main/frontend && npm i
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s ./settings.xml -Dgithub.token=${{ github.token}}
      env:
        GITHUB_TOKEN: ${{ github.token }}