name: Sync Develop with Main

on:
  push:
    branches:
      - main

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out develop branch
        run: git checkout develop

      - name: Merge main into develop
        run: git merge origin/main --no-edit

      - name: Push changes to develop
        run: git push origin develop
